function [ Legit ] = exception_handler(nameDataset,nameCalFolder,CorM,...
                     Temperature_Zero,Filter_Config,FIR_Runs,Timestep_Reduction)
%% Exception handler for NISI input arguments
Legit = 1; % Legit = 1 means configuration is legit

if ( CorM ~= 'C' && CorM ~= 'M' ) 
    fprintf(['\n\n\n\n\n\n Configuration is not legit!\n'...
             ' Second input for NISI-Function needs to be either\n' ...
             ' ''C'' (for calibration run) or ''M'' (for measurement run).\n' ...
             ' Exiting Program. \n'] )
    Legit = 0;
end

if ( Temperature_Zero == 0) 
    fprintf(['\n\n\n\n\n\n Configuration is not legit!\n Time in s used to equate' ...
             ' zero level temperature is not allowed to be 0. \n Exiting Program. \n'] )
    Legit = 0;
end

% Verwendung von FIR Filter aber 0 Filterruns eingestellt
if (( (Filter_Config(1) == (1||3||4)) && FIR_Runs(1) == 0 ) || ...
    ( (Filter_Config(2) == (1||3||4)) && FIR_Runs(2) == 0 ) || ...
    ( (Filter_Config(3) == (1||3||4)) && FIR_Runs(3) == 0 ) || ...
    ( (Filter_Config(4) == (1||3||4)) && FIR_Runs(4) == 0 ) || ...
    ( (Filter_Config(5) == (1||3||4)) && FIR_Runs(5) == 0 ) )  
    fprintf(['\n\n\n\n\n\n Configuration is not legit!\n Activating filter procedure' ...
             ' requires to allow for 1+ filter runs. \n Exiting Program. \n'] )
    Legit = 0;
end

% Entweder Cal Temp oder Cal HF nicht reduziert, der jeweils andere aber schon
if CorM == 'C' && ...
   xor(Filter_Config(1)==0,Filter_Config(2)==0) && ... % <- exactly one of the two = 0
   Timestep_Reduction ~= 1
    fprintf(['\n\n\n\n\n\n Configuration is not legit!\n Only one of the two' ...
             ' vectors calibration temperature or heat flux is filtered and' ...
             ' thus reduced. Filter/reduce either both or none of them to maintain' ...
             ' equal vector lengths! \n Exiting Program. \n'] )
    Legit = 0;
end

load pfade.mat
nameParameter = ([ pathDataFolder nameDataset '\' nameCalFolder '\' ...
                     nameDataset '_' nameCalFolder '_C_NISI_Parameter.mat' ]);
pathCalFolder =  ([ pathDataFolder nameDataset '\' nameCalFolder '\' ]);      
if CorM == 'M' && (exist(nameParameter,'file') == 0)
    fprintf(['\n\n\n\n\n\n Cannot find calibration files in given calibration folder.'...
             ' Calibration folder expected in path: \n %s\n'...
             ' If the calibration run has not yet been performed, call'...
             ' NISI(nameDataset,''C'') to do so!\n'...
             ' Exiting Program. \n'], pathCalFolder )
    Legit = 0;
end

end